---
title: "Investigation of the regulation of antisense RNA in *Saccharomyces cerevisiae*."
---

Genomes of many different organisms show pervasive transcription. Protein-coding transcripts make up only a small part of the genome, and many other transcripts have been detected. It is still an outstanding question if and to what degree such transcripts carry out functional roles. Among the most prevalent noncoding RNAs are those transcribed from the strand opposite to that of an annotated coding gene, referred to as antisense transcripts.
In this thesis, I set out to investigate the functional role of antisense transcription in a model sys- tem, the yeast gene YKL151C. This gene encodes an NAD(P)H repair enzyme and forms a tandem (head-to-tail) gene pair with the downstream glycolysis gene GPM1. The region between these genes functions as a bidirectional promoter, regulating both downstream sense and upstream anti- sense RNA. Experiments to test for cis-regulatory functions of the antisense confirm its role as a repressive factor in the regulation of YKL151C: when the transcription factor Gcr2, or its putative binding site in the intergenic region, is deleted, GPM1 expression and YKL151C antisense (YKL151C_as) expression decreases, whereas YKL151C sense expression increases. Likewise, when putative binding sites for the early termination complex Nrd1-Nab3-Sen1 are deleted in YKL151C_as, antisense expression goes up and YKL151C expression drops. These data all support a model in which YKL51C_as is regulated by the transcription factor Gcr2 and represses the over- lapping sense transcript.
In my master’s research, I first aimed to investigate the condition specificity of YKL151C_as. I switched cells between glucose and glycerol media and observed that YKL151C_as expression and GPM1 expression increased while YKL151C mRNA levels declined. I next sought to explore the independent regulation of YKL151C and its antisense. I deleted the histone deacetylase Rpd3L components Pho23 and Rxt2, which are critical for the regulation of YKL151C. I found that YKL151C mRNA expression was impacted by this mutation, but not YKL151C_as, providing ev- idence against a model in which YKL151C represses the antisense instead of vice versa. In an additional line of experiments to investigate the mechanism of action of YKL151C_as, I measured the expression of endogenous YKL151C mRNA in the presence of a plasmid which expressed YKL151C_as, but could not detect evidence for trans-regulatory effects of YKL151C_as, sugges- tive of a cis-acting mechanism for this transcript.
Taken together, my findings establish YKL151C_as as an independently regulated, repressive an- tisense that enables the coordinated expression of the two flanking mRNAs in opposing conditions.