---
title: "Brown Fat gene expression Data"
---

I used the processed gene expression data from this [GEO](https://www.ncbi.nlm.nih.gov//geo/query/acc.cgi?acc=GSE129687) dataset published in this [paper](https://www.cell.com/cell-metabolism/fulltext/S1550-4131(19)30197-4?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS1550413119301974%3Fshowall%3Dtrue) to make a volcano plot of showing the gene expression changes between WT brown fat and the mutant used in the paper.

```{r setup, echo=FALSE,include=FALSE,warning = FALSE}
setwd('~/Google Drive/GeneExpressionDatasets')


library(ggplot2)
library(GEOquery)
library(ggrepel)
library(ggiraph)
library(tidyr)
library(plyr)

GSE129687_brown_wild_v_mut.deseq <- readLines("GSE129687_brown_wild_v_mut.deseq.csv.gz")
GSE129687_brown_wild_v_mut.deseq <- as.data.frame(GSE129687_brown_wild_v_mut.deseq)



GSE129687_brown_wild_v_mut.deseq3 <-separate(data = GSE129687_brown_wild_v_mut.deseq,sep = ',',col = 'GSE129687_brown_wild_v_mut.deseq',
                                             into = c('id','baseMean','log2FoldChange','lfcSE','stat','pvalue','padj'))
GSE129687_brown_wild_v_mut.deseq3 <- GSE129687_brown_wild_v_mut.deseq3[-1,]
GSE129687_brown_wild_v_mut.deseq3$log2FoldChange <- as.numeric(GSE129687_brown_wild_v_mut.deseq3$log2FoldChange)
GSE129687_brown_wild_v_mut.deseq3$padj <- as.numeric(GSE129687_brown_wild_v_mut.deseq3$padj)
GSE129687_brown_wild_v_mut.deseq3$pvalue <- as.numeric(GSE129687_brown_wild_v_mut.deseq3$pvalue)
GSE129687_brown_wild_v_mut.deseq3$baseMean <- as.numeric(GSE129687_brown_wild_v_mut.deseq3$baseMean)


POIs <- c('Gck','Actn1','Gapdh','Pparg')


GSE129687_brown_wild_v_mut.deseq3$POI2 <- F
GSE129687_brown_wild_v_mut.deseq3$POI2 <-  ifelse(
  test =  grepl( paste(x=POIs,collapse="|"), x= GSE129687_brown_wild_v_mut.deseq3$id), 
  yes= T,
  no= GSE129687_brown_wild_v_mut.deseq3$POI2
)
GSE129687_brown_wild_v_mut.deseq3$POI <- NA
GSE129687_brown_wild_v_mut.deseq3$POI <-  ifelse(
  test =  GSE129687_brown_wild_v_mut.deseq3$POI2, 
  yes= GSE129687_brown_wild_v_mut.deseq3$id,
  no= GSE129687_brown_wild_v_mut.deseq3$POI
)

GSE129687_brown_wild_v_mut.deseq4 <- subset(GSE129687_brown_wild_v_mut.deseq3, POI2==F)
GSE129687_brown_wild_v_mut.deseq5 <- subset(GSE129687_brown_wild_v_mut.deseq3, POI2==T)
GSE129687_brown_wild_v_mut.deseq6 <- rbind.fill(GSE129687_brown_wild_v_mut.deseq4,GSE129687_brown_wild_v_mut.deseq5)

GSE129687_brown_wild_v_mut.deseq6$gene_link <- sprintf("window.open(\"%s%s\")",'https://www.genecards.org/cgi-bin/carddisp.pl?gene=',
                                                       GSE129687_brown_wild_v_mut.deseq6$id)



GSE129687_brown_wild_v_mut.deseq4 <- subset(GSE129687_brown_wild_v_mut.deseq3, POI2==F)
GSE129687_brown_wild_v_mut.deseq5 <- subset(GSE129687_brown_wild_v_mut.deseq3, POI2==T)
GSE129687_brown_wild_v_mut.deseq6 <- rbind.fill(GSE129687_brown_wild_v_mut.deseq4,GSE129687_brown_wild_v_mut.deseq5)

GSE129687_brown_wild_v_mut.deseq6$gene_link <- sprintf("window.open(\"%s%s\")",'https://www.genecards.org/cgi-bin/carddisp.pl?gene=',
                                                       GSE129687_brown_wild_v_mut.deseq6$id)


gse2 <- ggplot()+

  geom_point_interactive(data=GSE129687_brown_wild_v_mut.deseq6, aes(x=log2FoldChange , y=-log10(pvalue) ,
                                          # size=control_group_fpkm,
                                           tooltip=id
                                          , color=POI2
                                          
                                          # ,data_id=significant.low500vshigh600.
                                           ,onclick=gene_link
  ) 
  ,alpha=0.6,show.legend=F)+
 # labs(size = "Transcripts (FPKM)", color="Significant change in\n 200 mosmo/l sucrose")+
  xlab('log2 fold change')+
  ylab('-log10 adj. p-value')+
  scale_color_manual(values=c('black','red'))+
  ggrepel::geom_label_repel(data=GSE129687_brown_wild_v_mut.deseq6, aes(x=log2FoldChange , y=-log10(pvalue) ,label=POI))+
  # xlim(c(0,300))+
  # ylim(c(-8,8))+
  ggtitle('Gene expression changes in brown fat vs. mutant')+
  # ylim(c(-10,320))+
  theme_classic()


gse3 <- ggplot()+

  geom_point_interactive(data=GSE129687_brown_wild_v_mut.deseq6, aes(x=log(baseMean) , y=log2FoldChange ,                                                                  
                                           size=-log10(pvalue),
                                           tooltip=id
                                          , color=POI2
                                          
                                          # ,data_id=significant.low500vshigh600.
                                           ,onclick=gene_link
  ) 
  ,alpha=0.3,show.legend=F)+
 # labs(size = "Transcripts (FPKM)", color="Significant change in\n 200 mosmo/l sucrose")+
 # xlab('log2 fold change')+
 # ylab('-log10 adj. p-value')+
  scale_color_manual(values=c('grey80','red'))+
  ggrepel::geom_label_repel(data=GSE129687_brown_wild_v_mut.deseq6, aes(x=log(baseMean) , y=log2FoldChange ,label=POI))+
   ylim(c(-1,1))+
  # ylim(c(-8,8))+
  ggtitle('Gene expression changes in brown fat vs. mutant')+
  # ylim(c(-10,320))+
  theme_classic()



gluco <- as.numeric(GSE129687_brown_wild_v_mut.deseq5$baseMean)

gse4 <-ggplot()+
 # geom_density(data = GSE129687_brown_wild_v_mut.deseq6,mapping = aes(x = log(baseMean)))+
geom_histogram(data = GSE129687_brown_wild_v_mut.deseq6,mapping = aes(x = log(baseMean)))+
  geom_vline_interactive(xintercept = log(gluco),tooltip=unique(GSE129687_brown_wild_v_mut.deseq6$POI)[-1],color='red')+
  theme_classic()





```


```{r plotbox, echo=FALSE,warning = FALSE,comment=F,message=F}
girafe(ggobj = gse2) %>%
girafe_options(opts_zoom(max = 5),
               opts_tooltip(use_fill = TRUE))

```

```{r plotbox2, echo=FALSE,warning = FALSE,comment=F,message=F}
girafe(ggobj = gse3) %>%
girafe_options(opts_zoom(max = 5),
               opts_tooltip(use_fill = TRUE))

```

```{r plotbox3, echo=FALSE,warning = FALSE,comment=F,message=F}
girafe(ggobj = gse4) %>%
  girafe_options(opts_zoom(max = 5),
                 opts_tooltip(use_fill = TRUE))

```
